import Papa from "papaparse";
import { ROUND2_COLUMNS, ROUND2_COMMENTS, ROUND2_REFLECTIONS } from "@/lib/round2/form";
type Key = keyof typeof ROUND2_COLUMNS;
export type Round2CsvRow = { applicantCode: string; interviewerId: string; role: string; submittedAt: string; behavioralScore: number; challengeScore: number; altruism: number; grit: number; teamPlayer: number; expertise: number; communitySeeker: number; communityBuilder: number; finalDecision: string; comments: Record<string, string>; reflections: Record<string, string> };
const norm = (value: string) => value.replace(/[\u2018\u2019]/g, "'").replace(/[\u201c\u201d]/g, '"').replace(/\s+/g, " ").trim().toLowerCase();
export function parseRound2Csv(csv: string): Round2CsvRow[] {
  const parsed = Papa.parse<string[]>(csv.trim(), { skipEmptyLines: "greedy" }); if (parsed.errors.length || !parsed.data.length) throw new Error(parsed.errors[0]?.message ?? "Could not read the CSV.");
  const [headers, ...rows] = parsed.data; const map = {} as Record<Key, number>; const normalized = headers.map(norm);
  for (const [key, stem] of Object.entries(ROUND2_COLUMNS) as Array<[Key, string]>) { const matches = normalized.map((header, index) => ({ header, index })).filter((x) => x.header.startsWith(stem)); if (matches.length !== 1) throw new Error(`${matches.length ? "Multiple" : "No"} columns match "${stem}".`); map[key] = matches[0].index; }
  const scoreKeys = ["behavioralScore", "challengeScore", "altruism", "grit", "teamPlayer", "expertise", "communitySeeker", "communityBuilder"] as const;
  return rows.map((row, index) => { const get = (key: Key) => row[map[key]]?.trim() ?? ""; if (!get("applicantCode") && !get("interviewerId")) return null; const scores = Object.fromEntries(scoreKeys.map((key) => [key, Number(get(key))])) as Pick<Round2CsvRow, typeof scoreKeys[number]>; if (!get("applicantCode") || !get("interviewerId") || !get("timestamp")) throw new Error(`Row ${index + 2} is missing required information.`); if (scoreKeys.some((key) => !Number.isInteger(scores[key]) || scores[key] < 1 || scores[key] > 4)) throw new Error(`Row ${index + 2} has a score outside 1–4.`); const decision = norm(get("finalDecision")).replace(/^lean reject$/, "lean deny").replace(/^reject$/, "deny").replace(" ", "_"); if (!["admit", "lean_admit", "lean_deny", "deny"].includes(decision)) throw new Error(`Row ${index + 2} has an unrecognized final decision.`); return { applicantCode: get("applicantCode"), interviewerId: get("interviewerId"), role: norm(get("role")), submittedAt: get("timestamp"), ...scores, finalDecision: decision, comments: Object.fromEntries(ROUND2_COMMENTS.map(([key]) => [key, get(key)])), reflections: Object.fromEntries(ROUND2_REFLECTIONS.map(([key]) => [key, get(key)])) }; }).filter((row): row is Round2CsvRow => Boolean(row));
}
