"use client";
import { Fragment, useMemo, useState } from "react";
import { ChevronDownIcon, ChevronUpIcon, EyeIcon, EyeOffIcon } from "lucide-react";
import type { Round1Applicant } from "@/lib/actions/round1";
import { Button } from "@/components/ui/button";
import { ApplicantWrittenProfile } from "@/components/applicant-written-profile";
import { Round1Stats } from "@/components/round1-stats";
import { Round1DecisionSelect } from "@/components/round1-decision-select";
export function Round1Table({ activeSetId, applicants }: { activeSetId: string; applicants: Round1Applicant[] }) { const [expanded, setExpanded] = useState<string | null>(null); const [showNames, setShowNames] = useState(false); const [descending, setDescending] = useState(true); const rows = useMemo(() => [...applicants].sort((a, b) => (descending ? 1 : -1) * ((b.total ?? -1) - (a.total ?? -1))), [applicants, descending]); const interviewer = (row: Round1Applicant, role: string) => row.interviews.find((item) => item.role === role); return <div className="flex flex-col gap-5"><div className="flex items-center justify-between"><div><h2 className="font-heading text-lg font-semibold text-brand-dark">Round 1 deliberation</h2><p className="text-sm text-muted-foreground">Two interviews per applicant, scored out of 64.</p></div><Button variant="outline" size="sm" onClick={() => setShowNames(!showNames)}>{showNames ? <EyeOffIcon /> : <EyeIcon />}{showNames ? "Hide names" : "Show names"}</Button></div><div className="overflow-x-auto rounded-2xl border border-border bg-card"><table className="w-full min-w-[950px] text-sm"><thead className="bg-muted/45 text-left text-xs font-medium tracking-wide text-muted-foreground uppercase"><tr><th className="w-9 p-3" /><th className="p-3">Applicant</th><th className="p-3">Grad year</th><th className="p-3">Lead</th><th className="p-3">Notetaker</th><th className="p-3"><button onClick={() => setDescending(!descending)}>Score {descending ? "↓" : "↑"}</button></th><th className="p-3">Lead decision</th><th className="p-3">Notetaker decision</th><th className="p-3">Status</th></tr></thead><tbody>{rows.map((row) => { const open = expanded === row.id; const lead = interviewer(row, "lead"); const note = interviewer(row, "notetaker"); return <Fragment key={row.id}><tr className="border-t border-border hover:bg-muted/25"><td className="p-3"><button className="rounded p-1 hover:bg-muted" aria-label="Toggle applicant details" onClick={() => setExpanded(open ? null : row.id)}>{open ? <ChevronUpIcon className="size-4" /> : <ChevronDownIcon className="size-4" />}</button></td><td className="p-3 font-medium text-brand-dark">{showNames ? row.fullName : row.name}</td><td className="p-3">{row.graduationYear ?? "—"}</td><td className="p-3">{lead?.interviewerId ?? "—"}</td><td className="p-3">{note?.interviewerId ?? "—"}</td><td className="p-3 font-semibold tabular-nums">{row.total ?? "—"}{row.total ? "/64" : ""}</td><td className="p-3">{label(lead?.finalDecision)}</td><td className="p-3">{label(note?.finalDecision)}</td><td className="p-3"><Round1DecisionSelect activeSetId={activeSetId} applicantId={row.id} decision={row.decision} /></td></tr>{open ? <tr className="border-t border-border bg-muted/25"><td colSpan={9} className="p-5"><div className="grid gap-4 xl:grid-cols-2"><ApplicantWrittenProfile applicantId={row.id} /><Round1Stats interviews={row.interviews} /></div></td></tr> : null}</Fragment>; })}</tbody></table></div></div>; }
function label(value: string | undefined) { return value ? value.replaceAll("_", " ") : "—"; }
